un-hide all of the org.codehaus.plexus.util.xml (xpp3 and associated classes) so we avoid NoSuchMethodError's when using a method that references XmlPullParser, etc.
git-svn-id: https://svn.sonatype.org/spice/trunk@113 5751e0cb-dcb7-432f-92e2-260806df54be